spring.application.name=notification-service
server.port=9013

spring.datasource.url=jdbc:postgresql://notification-db:5432/notification_db
spring.datasource.username=user
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true


spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest