services:

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - linkedin-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - linkedin-network

  # ---------------- DATABASES ----------------

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - user-db-data:/var/lib/postgresql
    networks:
      - linkedin-network

  post-db:
    image: postgres
    container_name: post-db
    environment:
      - POSTGRES_DB=post_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - post-db-data:/var/lib/postgresql
    networks:
      - linkedin-network

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - notification-db-data:/var/lib/postgresql
    networks:
      - linkedin-network

  connection-db:
    image: neo4j
    container_name: connection-db
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - connection-db-data:/data
    networks:
      - linkedin-network

  # ---------------- DISCOVERY ----------------

  discovery-server:
    image: priyanshuraj354/linkedin-app/discovery-service:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - linkedin-network

  # ---------------- SERVICES ----------------

  user-service:
    image: priyanshuraj354/linkedin-app/user-service:latest
    container_name: user-service
    depends_on:
      - discovery-server
      - user-db
      - kafka
    networks:
      - linkedin-network

  post-service:
    image: priyanshuraj354/linkedin-app/post-service:latest
    container_name: post-service
    depends_on:
      - discovery-server
      - post-db
      - kafka
    networks:
      - linkedin-network

  notification-service:
    image: priyanshuraj354/linkedin-app/notification-service:latest
    container_name: notification-service
    depends_on:
      - discovery-server
      - notification-db
      - kafka
    networks:
      - linkedin-network

  connection-service:
    image: priyanshuraj354/linkedin-app/connection-service:latest
    container_name: connection-service
    depends_on:
      - discovery-server
      - connection-db
      - kafka
    networks:
      - linkedin-network

  # ---------------- API GATEWAY ----------------

  api-gateway:
    image: priyanshuraj354/linkedin-app/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - discovery-server
    networks:
      - linkedin-network
    ports:
      - "8081:8085"

# ---------------- VOLUMES ----------------

volumes:
  user-db-data:
  post-db-data:
  notification-db-data:
  connection-db-data:

# ---------------- NETWORK ----------------

networks:
  linkedin-network: