apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  username: user
  password: password

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt-secret-key: a;fkdsfirnafsanajganfugrpgj4ng9-pqw4fg-rngjsr08ue;gbs-rep;gus;9watgb
