spring.application.name=user-service

jwt.secretKey=a;fkdsfirnafsanajganfugrpgj4ng9-pqw4fg-rngjsr08ue;gbs-rep;gus;9watgb

server.port=9011
server.servlet.context-path=/users

spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=user
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# Actuator — liveness & readiness probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true